import { LanguageCodeType } from "./types";

export const languages: LanguageCodeType = {
  af: "Afrikaans",
  sq: "Albanian",
  am: "Amharic",
  ar: "Arabic",
  "ar-SA": "Arabic (Saudi Arabia)",
  "ar-AE": "Arabic (United Arab Emirates)",
  "ar-EG": "Arabic (Egypt)",
  hy: "Armenian",
  az: "Azerbaijani",
  eu: "Basque",
  be: "Belarusian",
  bn: "Bengali",
  bs: "Bosnian",
  bg: "Bulgarian",
  my: "Burmese",
  ca: "Catalan",
  zh: "Chinese",
  "zh-CN": "Chinese (Simplified, China)",
  "zh-TW": "Chinese (Traditional, Taiwan)",
  "zh-HK": "Chinese (Hong Kong)",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  "nl-NL": "Dutch (Netherlands)",
  "nl-BE": "Dutch (Belgium)",
  en: "English",
  "en-US": "English (United States)",
  "en-GB": "English (United Kingdom)",
  "en-CA": "English (Canada)",
  "en-AU": "English (Australia)",
  et: "Estonian",
  fi: "Finnish",
  fr: "French",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canada)",
  "fr-BE": "French (Belgium)",
  "fr-CH": "French (Switzerland)",
  gl: "Galician",
  ka: "Georgian",
  de: "German",
  "de-DE": "German (Germany)",
  "de-AT": "German (Austria)",
  "de-CH": "German (Switzerland)",
  el: "Greek",
  gu: "Gujarati",
  he: "Hebrew",
  "he-IL": "Hebrew (Israel)",
  hi: "Hindi",
  "hi-IN": "Hindi (India)",
  hu: "Hungarian",
  is: "Icelandic",
  id: "Indonesian",
  "id-ID": "Indonesian (Indonesia)",
  it: "Italian",
  "it-IT": "Italian (Italy)",
  "it-CH": "Italian (Switzerland)",
  ja: "Japanese",
  jv: "Javanese",
  kn: "Kannada",
  kk: "Kazakh",
  km: "Khmer",
  ko: "Korean",
  "ko-KR": "Korean (South Korea)",
  ky: "Kyrgyz",
  lo: "Lao",
  lv: "Latvian",
  lt: "Lithuanian",
  lb: "Luxembourgish",
  mk: "Macedonian",
  ms: "Malay",
  "ms-MY": "Malay (Malaysia)",
  "ms-SG": "Malay (Singapore)",
  ml: "Malayalam",
  mt: "Maltese",
  mn: "Mongolian",
  ne: "Nepali",
  no: "Norwegian",
  "no-NO": "Norwegian (Norway)",
  fa: "Persian",
  pl: "Polish",
  "pl-PL": "Polish (Poland)",
  pt: "Portuguese",
  "pt-PT": "Portuguese (Portugal)",
  "pt-BR": "Portuguese (Brazil)",
  pa: "Punjabi",
  ro: "Romanian",
  ru: "Russian",
  "ru-RU": "Russian (Russia)",
  "ru-UA": "Russian (Ukraine)",
  sr: "Serbian",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  es: "Spanish",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "es-AR": "Spanish (Argentina)",
  "es-CO": "Spanish (Colombia)",
  sw: "Swahili",
  sv: "Swedish",
  "sv-SE": "Swedish (Sweden)",
  "sv-FI": "Swedish (Finland)",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  "tr-TR": "Turkish (Turkey)",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  vi: "Vietnamese",
  "vi-VN": "Vietnamese (Vietnam)",
  cy: "Welsh",
  xh: "Xhosa",
  yi: "Yiddish",
  zu: "Zulu",
};
